[tool.poetry]
name = "vulnerabilitylookup"
version = "0.1"
description = "vulnerability-lookup is a rewrite of cve-search to support fast vulnerability lookup, independent vulnerability ID and easily manage coordinated vulnerability disclosure (CVD)."
authors = ["Alexandre Dulaunoy <alexandre.dulaunoy@circl.lu>", "Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
start = "bin.start:main"
stop = "bin.stop:main"
update = "bin.update:main"
shutdown = "bin.shutdown:main"
run_backend = "bin.run_backend:main"
start_website = "bin.start_website:main"

nvd = "bin.nvd_fetcher:main"
cisa_known_exploited = "bin.cisa_known_exploited:main"
gsd_importer = "bin.gsd:main"
pysec_importer = "bin.pysec:main"
github_importer = "bin.github:main"
dump = "bin.dump:main"

[tool.poetry.dependencies]
python = "^3.10"
redis = {version = "^5.0.1", extras = ["hiredis"]}
flask-restx = "^1.2.0"
werkzeug = "^2.3.7"
gunicorn = "^21.2.0"
requests = "^2.31.0"
gitpython = "^3.1.40"
bootstrap-flask = "^2.3.2"
pyyaml = "^6.0.1"

[tool.poetry.dev-dependencies]
ipython = "^8.17.2"
mypy = "^1.6.1"
types-redis = "^4.6.0.9"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.30.0.0"
types-pyyaml = "^6.0.12.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = false
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true
