[tool.poetry]
name = "vulnerabilitylookup"
version = "0.6.0"
description = "vulnerability-lookup is a rewrite of cve-search to support fast vulnerability lookup, independent vulnerability ID and easily manage coordinated vulnerability disclosure (CVD)."
authors = ["Alexandre Dulaunoy <alexandre.dulaunoy@circl.lu>", "Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
start = "bin.start:main"
stop = "bin.stop:main"
update = "bin.update:main"
shutdown = "bin.shutdown:main"
run_backend = "bin.run_backend:main"
start_website = "bin.start_website:main"

cisa_known_exploited = "bin.cisa_known_exploited:main"
nvd_importer = "bin.nvd_fetcher:main"
cvelist_importer = "bin.cvelist:main"
gsd_importer = "bin.gsd:main"
pysec_importer = "bin.pysec:main"
github_importer = "bin.github:main"
ossf_malicious_importer = "bin.ossf_malicious:main"
csaf_certbund_importer = "bin.csaf_certbund:main"
dump = "bin.dump:main"

[tool.poetry.dependencies]
python = "^3.10"
redis = {version = "^5.0.1", extras = ["hiredis"]}
flask-restx = "^1.3.0"
werkzeug = "^3.0.1"
gunicorn = "^21.2.0"
requests = "^2.31.0"
gitpython = "^3.1.42"
bootstrap-flask = "^2.3.3"
pyyaml = "^6.0.1"
orjson = "^3.9.14"
feedgen = "^1.0.0"

[tool.poetry.dev-dependencies]
ipython = "^8.21.0"
mypy = "^1.8.0"
types-redis = "^4.6.0.20240106"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.30.0.0"
types-pyyaml = "^6.0.12.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = false
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true
