[tool.poetry]
name = "vulnerabilitylookup"
version = "0.1"
description = "vulnerability-lookup is a rewrite of cve-search to support fast vulnerability lookup, independent vulnerability ID and easily manage coordinated vulnerability disclosure (CVD)."
authors = ["Alexandre Dulaunoy <alexandre.dulaunoy@circl.lu>", "Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
start = "bin.start:main"
stop = "bin.stop:main"
update = "bin.update:main"
shutdown = "bin.shutdown:main"
run_backend = "bin.run_backend:main"
start_website = "bin.start_website:main"

nvd = "bin.nvd_fetcher:main"

[tool.poetry.dependencies]
python = "^3.10"
redis = {version = "^4.5.5", extras = ["hiredis"]}
flask-restx = "^1.1.0"
werkzeug = "^2.3.4"
gunicorn = "^20.1.0"
requests = "^2.30.0"

[tool.poetry.dev-dependencies]
ipython = "^8.13.2"
mypy = "^1.3.0"
types-redis = "^4.5.5.2"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.30.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = false
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true
