name: Python application - API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install with poetry
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
        echo VULNERABILITYLOOKUP_HOME=`pwd` > .env

    - name: Install redis
      run: |
        pushd ..
        git clone https://github.com/redis/redis.git
        pushd redis
        git checkout 7.2
        make
        popd
        popd

    - name: Install kvrocks
      run: |
        sudo apt-get update
		sudo apt install -y git gcc g++ make cmake autoconf automake libtool python3 libssl-dev
        pushd ..
        git clone --recursive https://github.com/apache/incubator-kvrocks.git kvrocks
        pushd kvrocks
		git checkout 2.4
		./x.py build
        popd
        popd

    - name: Run API tests
      run: |
        poetry run start
		sleep 10

        # git clone https://github.com/Lookyloo/pyproject_template.git
        # pushd pyproject_template
        # poetry install
        # poetry run pytest tests/test_web.py
        # popd

        poetry run stop

    - name: Test update script
      run: |
        poetry run update --yes
        sleep 30
        poetry run stop
